# Generated by Django 6.0.7 on 2026-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokaccount',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
