# Generated by Django 6.0.7 on 2026-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_auth', '0002_alter_tiktokaccount_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokaccount',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
