# Generated by Django 6.0.7 on 2026-07-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_auth', '0003_alter_tiktokaccount_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('educational', 'Educational'), ('tutorial', 'Tutorial'), ('relatable', 'Relatable'), ('promotional', 'Promotional'), ('story', 'Story'), ('other', 'Other')], default='educational', max_length=30)),
                ('hook', models.CharField(blank=True, max_length=300)),
                ('script', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('planned_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Post'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ideas', to='tiktok_auth.tiktokaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
