# Generated by Django 6.0.7 on 2026-07-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_auth', '0004_contentidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='bio_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='follower_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='following_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='likes_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='profile_deep_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='video_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TikTokVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True)),
                ('video_description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('embed_link', models.URLField(blank=True, max_length=1000)),
                ('share_url', models.URLField(blank=True, max_length=1000)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('share_count', models.PositiveBigIntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tiktok_auth.tiktokaccount')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
