# Generated by Django 6.0.7 on 2026-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_auth', '0005_tiktokaccount_bio_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiktokvideo',
            options={'ordering': ['-posted_at', '-view_count']},
        ),
        migrations.RenameField(
            model_name='tiktokvideo',
            old_name='video_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='embed_link',
            field=models.URLField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='share_url',
            field=models.URLField(blank=True, max_length=1500),
        ),
    ]
